services:
  mariadb:
    image: mysql:8.4
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASS}"]
      interval: 15s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    image: posts-service
    build: .
    env_file:
      - ./.env
    ports:
      - "${SPRING_APP_PORT}:${DOCKER_APP_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mariadb:${MYSQL_DOCKER_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASS}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.MySQLDialect"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
